[build]
  publish = "public"            # Specify the folder to publish
  command = "npm run build"     # Build command (will run `vite build` for Vite)
  
[[redirects]]
  from = "/build/*"
  to = "/:splat"
  status = 200
  force = true
